import 'package:eatapp/data/supabase/account_code.dart';
import 'package:eatapp/data/supabase/identity.dart';

/// A hand-written [IdentityGateway] fake — no mocking package, per the
/// project's convention.
///
/// It simulates the pieces of Supabase auth the app actually touches: a device
/// either has an identity or it does not, [createAccount] mints a fresh code
/// and [signInWithCode] adopts one (reusing the same user id on later calls, as
/// the real backend does when the same code is adopted again), and [signOut]
/// forgets the session while keeping the code.
class FakeIdentityGateway implements IdentityGateway {
  FakeIdentityGateway({this.existingUserId, this.storedCode});

  /// Pre-set as if a session had been restored from disk; null means "this
  /// device has never signed in".
  String? existingUserId;

  /// Pre-set as if a code had been kept on disk, and updated by every successful
  /// [createAccount] / [signInWithCode].
  String? storedCode;

  /// The last code used — generated by [createAccount], or passed to
  /// [signInWithCode].
  String? lastCode;

  /// How many accounts were created.
  int createCount = 0;

  /// How many times a code was used to sign in.
  int signInCount = 0;

  /// The user id a successful sign-in mints, when the device had none.
  String providerUserId = 'fake-user-1';

  /// Throw to simulate a network/auth failure when creating or signing in.
  Object? createError;
  Object? signInError;

  @override
  Future<Identity?> current() async {
    final String? userId = existingUserId;
    if (userId == null) {
      return null;
    }
    return Identity(userId: userId, isSignedIn: true);
  }

  @override
  String? accountCode() => storedCode;

  @override
  Future<Identity> createAccount() async {
    final Object? error = createError;
    if (error != null) {
      throw error;
    }
    createCount++;
    storedCode = generateAccountCode();
    lastCode = storedCode;
    existingUserId ??= providerUserId;
    return Identity(userId: existingUserId!, isSignedIn: true);
  }

  @override
  Future<Identity> signInWithCode(String code) async {
    final Object? error = signInError;
    if (error != null) {
      throw error;
    }
    signInCount++;
    lastCode = code;
    storedCode = code;
    existingUserId ??= providerUserId;
    return Identity(userId: existingUserId!, isSignedIn: true);
  }

  @override
  Future<void> signOut() async {
    existingUserId = null;
    // The account code survives sign-out, as the real gateway keeps it.
  }
}
